spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MSTraining?createDatabaseIfNotExist=true
    username: testUser
    password: samplePass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"